// Autogenerated from Pigeon (v29.0.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// Mirrors the native `dev.brickvpn.harness.vpn.VpnState` sealed hierarchy —
/// all EIGHT variants, including the two with no Dart equivalent.
///
/// Do NOT "simplify" this to core_domain's five `ConnectionState` variants:
/// `Revoked` is Android-specific (ARCHITECTURE.md line 209: "VPN permission
/// revocation is an Android-specific concept") and must survive the bridge so
/// P3-T14 can map it to `Error(PermissionDenied)` explicitly.
enum VpnNativeState {
  idle,
  preparing,
  starting,
  running,
  stopping,
  stopped,
  error,
  revoked;
}

/// Mirrors native `dev.brickvpn.harness.vpn.VpnCommandResult` — all FIVE
/// variants, matching `core_vpn_engine`'s discriminators 1:1 (`accepted`,
/// `rejected_busy`, `rejected_invalid_config`, `rejected_permission_denied`,
/// `failed`).
///
/// Reachability note (recorded so no later task mistakes it for a bug): the
/// native `VpnStateMachine.start()` can currently return only `accepted` /
/// `rejectedBusy` / `rejectedPermissionDenied`, and `stop()` returns only
/// `accepted`, because no config validation exists on that path yet. The enum
/// still carries all five because `VpnCommandResult` is a *sealed* type in
/// Dart — omitting a variant would make P3-T14's exhaustive switch impossible
/// to write faithfully.
enum VpnCommandOutcome {
  accepted,
  rejectedBusy,
  rejectedInvalidConfig,
  rejectedPermissionDenied,
  failed;
}

/// Result of the Android VPN consent flow (`VpnService.prepare()`).
///
/// This is the P3-T12 AC3 addition: the original P1-T4 interface was written
/// before Android's consent dialog was in view, so it models no way to ASK for
/// permission — only a way to be REJECTED for lacking it. The distinction
/// between [alreadyGranted] and [granted] is preserved deliberately: UI code
/// needs to know whether it may prompt immediately or whether a rationale
/// screen should come first.
enum VpnConsentStatus {
  /// Consent was already held; no system dialog was shown.
  alreadyGranted,

  /// The system consent dialog was shown and the user accepted it.
  granted,

  /// The dialog was shown and refused (or consent was revoked since).
  /// `start()` will be rejected until consent is obtained.
  denied;
}

/// One emission of the connection-state event channel.
///
/// `errorReason` is non-null exactly when [state] is [VpnNativeState.error],
/// mirroring native `VpnState.Error(val reason: String)`. Keeping the reason
/// attached to the event (rather than on a side channel) makes each emission
/// self-contained and order-preserving.
class VpnStateEvent {
  VpnStateEvent({
    required this.state,
    this.errorReason,
  });

  VpnNativeState state;

  /// Native failure reason. Null unless [state] is `error`.
  String? errorReason;

  List<Object?> _toList() {
    return <Object?>[
      state,
      errorReason,
    ];
  }

  Object encode() {
    return _toList();
  }

  static VpnStateEvent decode(Object result) {
    result as List<Object?>;
    return VpnStateEvent(
      state: result[0]! as VpnNativeState,
      errorReason: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VpnStateEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(state, other.state) &&
        _deepEquals(errorReason, other.errorReason);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VpnStateEvent(state: $state, errorReason: $errorReason)';
  }
}

/// One emission of the traffic-stats event channel.
///
/// KNOWN GAP, DELIBERATE (P3-T8 is `Not Started`): the native engine has no
/// stats source yet — `TunnelEngine` exposes only `start(tunFd)`/`stop()`.
/// The channel exists so the transport shape is fixed now, but the Kotlin side
/// emits NOTHING on it until P3-T8 supplies a real reader. Emitting invented
/// zeros would look like "connected but idle", which is precisely the legacy
/// "traffic always 0 bytes" failure this project must not repeat. P3-T14
/// inherits this gap and must not present an empty stream as a measured zero.
class TrafficStatsEvent {
  TrafficStatsEvent({
    required this.txBytes,
    required this.rxBytes,
    required this.epochMillis,
  });

  /// Cumulative bytes sent through the tunnel.
  int txBytes;

  /// Cumulative bytes received through the tunnel.
  int rxBytes;

  /// When the counters were read, epoch milliseconds (UTC). Milliseconds
  /// rather than `DateTime` so the value survives the `StandardMessageCodec`
  /// round-trip identically without local-time-zone handling.
  int epochMillis;

  List<Object?> _toList() {
    return <Object?>[
      txBytes,
      rxBytes,
      epochMillis,
    ];
  }

  Object encode() {
    return _toList();
  }

  static TrafficStatsEvent decode(Object result) {
    result as List<Object?>;
    return TrafficStatsEvent(
      txBytes: result[0]! as int,
      rxBytes: result[1]! as int,
      epochMillis: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TrafficStatsEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(txBytes, other.txBytes) &&
        _deepEquals(rxBytes, other.rxBytes) &&
        _deepEquals(epochMillis, other.epochMillis);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'TrafficStatsEvent(txBytes: $txBytes, rxBytes: $rxBytes, epochMillis: $epochMillis)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is VpnNativeState) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is VpnCommandOutcome) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is VpnConsentStatus) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is VpnStateEvent) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is TrafficStatsEvent) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : VpnNativeState.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : VpnCommandOutcome.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : VpnConsentStatus.values[value];
      case 132:
        return VpnStateEvent.decode(readValue(buffer)!);
      case 133:
        return TrafficStatsEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec =
    StandardMethodCodec(_PigeonCodec());

/// Commands Flutter invokes on the Android host.
///
/// Acceptance is separate from final state (ARCHITECTURE.md Section 3.5,
/// lines 367-374): [start]/[stop] report only whether the command was accepted
/// for processing. The resulting transition arrives EXCLUSIVELY on the
/// `stateEvents` stream below and must never be inferred from these return
/// values.
class VpnEngineHostApi {
  /// Constructor for [VpnEngineHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  VpnEngineHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  })  : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix =
            messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Obtains Android's `VpnService` consent, prompting the user if needed.
  ///
  /// `@async` because showing the system dialog and waiting for the user is
  /// inherently asynchronous on the Kotlin side; a plain method would force
  /// the host implementation to block a thread on a UI dialog.
  ///
  /// Maps in P3-T14 to `core_vpn_engine`'s `VpnEngine.prepare()`:
  /// `alreadyGranted`/`granted` -> `VpnCommandAccepted`,
  /// `denied` -> `VpnCommandRejectedPermissionDenied`.
  Future<VpnConsentStatus> prepare() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.vpn_engine_android.VpnEngineHostApi.prepare$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as VpnConsentStatus;
  }

  /// Requests a tunnel start.
  ///
  /// [profileJson] is `ServerProfile.toJson()` from `core_domain` — NOT a
  /// Pigeon mirror of `ServerProfile`'s polymorphic `OutboundConfig`
  /// hierarchy. Serializing rather than re-modeling avoids inventing a second
  /// vocabulary for the same value (P1-T3 already proved `ServerProfile`
  /// round-trips losslessly through `toJson()`), and `core_domain` stays
  /// frozen.
  ///
  /// The type is `Map<String, Object?>` and deliberately NOT
  /// `Map<String, dynamic>`: Pigeon transcribes Dart `dynamic` verbatim into
  /// Kotlin `dynamic`, and Kotlin/JVM rejects that with
  /// "Dynamic type is only supported in Kotlin JS" — a JVM compile error that
  /// only appears once the generated file is compiled, not when Pigeon runs.
  ///
  /// KNOWN GAP for P3-T14/P3-T15: the native engine cannot consume this yet.
  /// `TunnelEngine.start(tunFd: Int)` takes no config and
  /// `LibboxTunnelEngine.configJsonProvider` defaults to the hardcoded
  /// `GATE_A_CONFIG_JSON`. P3-T15's own scope says to keep the hardcoded
  /// config for now, so the profile is carried faithfully across the bridge
  /// and deliberately not yet consumed. It must NOT be dropped here: doing so
  /// would lose information the contract requires.
  Future<VpnCommandOutcome> start(Map<String, Object?> profileJson) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.vpn_engine_android.VpnEngineHostApi.start$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[profileJson]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as VpnCommandOutcome;
  }

  /// Requests a tunnel stop. Same acceptance semantics as [start].
  Future<VpnCommandOutcome> stop() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.vpn_engine_android.VpnEngineHostApi.stop$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as VpnCommandOutcome;
  }

  /// Point-in-time state read for callers that are not subscribed (e.g. after
  /// a process restart, before the UI settles on an initial display).
  Future<VpnStateEvent> getStatus() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.vpn_engine_android.VpnEngineHostApi.getStatus$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as VpnStateEvent;
  }
}

/// Host -> Flutter push streams.
///
/// Two structurally SEPARATE channels, not one multiplexed channel:
/// `core_vpn_engine`'s `VpnEngine` Invariant 2 requires that a failure in the
/// statistics pipeline can never block or corrupt the connection-state
/// pipeline. Sharing a channel would re-couple them at the transport layer and
/// silently violate that invariant.
///
/// Pigeon 29.0.6 generates a real `io.flutter.plugin.common.EventChannel` for
/// these (verified against the installed package, not assumed) — no hand-rolled
/// EventChannel and no method-channel polling.
/// Every state transition, in order.
///
/// Returns a broadcast [Stream] of events from the `stateEvents` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<VpnStateEvent> stateEvents({String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel stateEventsChannel = EventChannel(
      'dev.flutter.pigeon.vpn_engine_android.VpnEngineEventChannels.stateEvents$instanceName',
      pigeonMethodCodec);
  return stateEventsChannel.receiveBroadcastStream().map((dynamic event) {
    return event as VpnStateEvent;
  });
}

/// Traffic snapshots. Emits nothing until P3-T8 lands — see `TrafficStatsEvent`.
///
/// Returns a broadcast [Stream] of events from the `trafficStatsEvents` event channel.
///
/// Each call to this method creates a new [EventChannel], so it should
/// not be called multiple times for the same `instanceName`. To deliver
/// events to multiple listeners, call this method once and listen to the
/// returned broadcast stream multiple times instead.
Stream<TrafficStatsEvent> trafficStatsEvents({String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel trafficStatsEventsChannel = EventChannel(
      'dev.flutter.pigeon.vpn_engine_android.VpnEngineEventChannels.trafficStatsEvents$instanceName',
      pigeonMethodCodec);
  return trafficStatsEventsChannel
      .receiveBroadcastStream()
      .map((dynamic event) {
    return event as TrafficStatsEvent;
  });
}
