// Autogenerated from Pigeon (v29.0.6), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.brickvpn.harness.vpn

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object VpnEngineApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * Mirrors the native `dev.brickvpn.harness.vpn.VpnState` sealed hierarchy —
 * all EIGHT variants, including the two with no Dart equivalent.
 *
 * Do NOT "simplify" this to core_domain's five `ConnectionState` variants:
 * `Revoked` is Android-specific (ARCHITECTURE.md line 209: "VPN permission
 * revocation is an Android-specific concept") and must survive the bridge so
 * P3-T14 can map it to `Error(PermissionDenied)` explicitly.
 */
enum class VpnNativeState(val raw: Int) {
  IDLE(0),
  PREPARING(1),
  STARTING(2),
  RUNNING(3),
  STOPPING(4),
  STOPPED(5),
  ERROR(6),
  REVOKED(7);

  companion object {
    fun ofRaw(raw: Int): VpnNativeState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Mirrors native `dev.brickvpn.harness.vpn.VpnCommandResult` — all FIVE
 * variants, matching `core_vpn_engine`'s discriminators 1:1 (`accepted`,
 * `rejected_busy`, `rejected_invalid_config`, `rejected_permission_denied`,
 * `failed`).
 *
 * Reachability note (recorded so no later task mistakes it for a bug): the
 * native `VpnStateMachine.start()` can currently return only `accepted` /
 * `rejectedBusy` / `rejectedPermissionDenied`, and `stop()` returns only
 * `accepted`, because no config validation exists on that path yet. The enum
 * still carries all five because `VpnCommandResult` is a *sealed* type in
 * Dart — omitting a variant would make P3-T14's exhaustive switch impossible
 * to write faithfully.
 */
enum class VpnCommandOutcome(val raw: Int) {
  ACCEPTED(0),
  REJECTED_BUSY(1),
  REJECTED_INVALID_CONFIG(2),
  REJECTED_PERMISSION_DENIED(3),
  FAILED(4);

  companion object {
    fun ofRaw(raw: Int): VpnCommandOutcome? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Result of the Android VPN consent flow (`VpnService.prepare()`).
 *
 * This is the P3-T12 AC3 addition: the original P1-T4 interface was written
 * before Android's consent dialog was in view, so it models no way to ASK for
 * permission — only a way to be REJECTED for lacking it. The distinction
 * between [alreadyGranted] and [granted] is preserved deliberately: UI code
 * needs to know whether it may prompt immediately or whether a rationale
 * screen should come first.
 */
enum class VpnConsentStatus(val raw: Int) {
  /** Consent was already held; no system dialog was shown. */
  ALREADY_GRANTED(0),
  /** The system consent dialog was shown and the user accepted it. */
  GRANTED(1),
  /**
   * The dialog was shown and refused (or consent was revoked since).
   * `start()` will be rejected until consent is obtained.
   */
  DENIED(2);

  companion object {
    fun ofRaw(raw: Int): VpnConsentStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * One emission of the connection-state event channel.
 *
 * `errorReason` is non-null exactly when [state] is [VpnNativeState.error],
 * mirroring native `VpnState.Error(val reason: String)`. Keeping the reason
 * attached to the event (rather than on a side channel) makes each emission
 * self-contained and order-preserving.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class VpnStateEvent (
  val state: VpnNativeState,
  /** Native failure reason. Null unless [state] is `error`. */
  val errorReason: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VpnStateEvent {
      val state = pigeonVar_list[0] as VpnNativeState
      val errorReason = pigeonVar_list[1] as String?
      return VpnStateEvent(state, errorReason)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      state,
      errorReason,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VpnStateEvent
    return VpnEngineApiPigeonUtils.deepEquals(this.state, other.state) && VpnEngineApiPigeonUtils.deepEquals(this.errorReason, other.errorReason)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VpnEngineApiPigeonUtils.deepHash(this.state)
    result = 31 * result + VpnEngineApiPigeonUtils.deepHash(this.errorReason)
    return result
  }
  override fun toString(): String {
    return "VpnStateEvent(state=$state, errorReason=$errorReason)"
  }
}

/**
 * One emission of the traffic-stats event channel.
 *
 * KNOWN GAP, DELIBERATE (P3-T8 is `Not Started`): the native engine has no
 * stats source yet — `TunnelEngine` exposes only `start(tunFd)`/`stop()`.
 * The channel exists so the transport shape is fixed now, but the Kotlin side
 * emits NOTHING on it until P3-T8 supplies a real reader. Emitting invented
 * zeros would look like "connected but idle", which is precisely the legacy
 * "traffic always 0 bytes" failure this project must not repeat. P3-T14
 * inherits this gap and must not present an empty stream as a measured zero.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class TrafficStatsEvent (
  /** Cumulative bytes sent through the tunnel. */
  val txBytes: Long,
  /** Cumulative bytes received through the tunnel. */
  val rxBytes: Long,
  /**
   * When the counters were read, epoch milliseconds (UTC). Milliseconds
   * rather than `DateTime` so the value survives the `StandardMessageCodec`
   * round-trip identically without local-time-zone handling.
   */
  val epochMillis: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): TrafficStatsEvent {
      val txBytes = pigeonVar_list[0] as Long
      val rxBytes = pigeonVar_list[1] as Long
      val epochMillis = pigeonVar_list[2] as Long
      return TrafficStatsEvent(txBytes, rxBytes, epochMillis)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      txBytes,
      rxBytes,
      epochMillis,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as TrafficStatsEvent
    return VpnEngineApiPigeonUtils.deepEquals(this.txBytes, other.txBytes) && VpnEngineApiPigeonUtils.deepEquals(this.rxBytes, other.rxBytes) && VpnEngineApiPigeonUtils.deepEquals(this.epochMillis, other.epochMillis)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VpnEngineApiPigeonUtils.deepHash(this.txBytes)
    result = 31 * result + VpnEngineApiPigeonUtils.deepHash(this.rxBytes)
    result = 31 * result + VpnEngineApiPigeonUtils.deepHash(this.epochMillis)
    return result
  }
  override fun toString(): String {
    return "TrafficStatsEvent(txBytes=$txBytes, rxBytes=$rxBytes, epochMillis=$epochMillis)"
  }
}
private open class VpnEngineApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          VpnNativeState.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          VpnCommandOutcome.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          VpnConsentStatus.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VpnStateEvent.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          TrafficStatsEvent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is VpnNativeState -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is VpnCommandOutcome -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is VpnConsentStatus -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is VpnStateEvent -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is TrafficStatsEvent -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val VpnEngineApiPigeonMethodCodec = StandardMethodCodec(VpnEngineApiPigeonCodec())


/**
 * Commands Flutter invokes on the Android host.
 *
 * Acceptance is separate from final state (ARCHITECTURE.md Section 3.5,
 * lines 367-374): [start]/[stop] report only whether the command was accepted
 * for processing. The resulting transition arrives EXCLUSIVELY on the
 * `stateEvents` stream below and must never be inferred from these return
 * values.
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface VpnEngineHostApi {
  /**
   * Obtains Android's `VpnService` consent, prompting the user if needed.
   *
   * `@async` because showing the system dialog and waiting for the user is
   * inherently asynchronous on the Kotlin side; a plain method would force
   * the host implementation to block a thread on a UI dialog.
   *
   * Maps in P3-T14 to `core_vpn_engine`'s `VpnEngine.prepare()`:
   * `alreadyGranted`/`granted` -> `VpnCommandAccepted`,
   * `denied` -> `VpnCommandRejectedPermissionDenied`.
   */
  suspend fun prepare(): VpnConsentStatus
  /**
   * Requests a tunnel start.
   *
   * [profileJson] is `ServerProfile.toJson()` from `core_domain` — NOT a
   * Pigeon mirror of `ServerProfile`'s polymorphic `OutboundConfig`
   * hierarchy. Serializing rather than re-modeling avoids inventing a second
   * vocabulary for the same value (P1-T3 already proved `ServerProfile`
   * round-trips losslessly through `toJson()`), and `core_domain` stays
   * frozen.
   *
   * The type is `Map<String, Object?>` and deliberately NOT
   * `Map<String, dynamic>`: Pigeon transcribes Dart `dynamic` verbatim into
   * Kotlin `dynamic`, and Kotlin/JVM rejects that with
   * "Dynamic type is only supported in Kotlin JS" — a JVM compile error that
   * only appears once the generated file is compiled, not when Pigeon runs.
   *
   * KNOWN GAP for P3-T14/P3-T15: the native engine cannot consume this yet.
   * `TunnelEngine.start(tunFd: Int)` takes no config and
   * `LibboxTunnelEngine.configJsonProvider` defaults to the hardcoded
   * `GATE_A_CONFIG_JSON`. P3-T15's own scope says to keep the hardcoded
   * config for now, so the profile is carried faithfully across the bridge
   * and deliberately not yet consumed. It must NOT be dropped here: doing so
   * would lose information the contract requires.
   */
  fun start(profileJson: Map<String, Any?>): VpnCommandOutcome
  /** Requests a tunnel stop. Same acceptance semantics as [start]. */
  fun stop(): VpnCommandOutcome
  /**
   * Point-in-time state read for callers that are not subscribed (e.g. after
   * a process restart, before the UI settles on an initial display).
   */
  fun getStatus(): VpnStateEvent

  companion object {
    /** The codec used by VpnEngineHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      VpnEngineApiPigeonCodec()
    }
    /** Sets up an instance of `VpnEngineHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: VpnEngineHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vpn_engine_android.VpnEngineHostApi.prepare$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.prepare())
              } catch (exception: Throwable) {
                VpnEngineApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vpn_engine_android.VpnEngineHostApi.start$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val profileJsonArg = args[0] as Map<String, Any?>
            val wrapped: List<Any?> = try {
              listOf(api.start(profileJsonArg))
            } catch (exception: Throwable) {
              VpnEngineApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vpn_engine_android.VpnEngineHostApi.stop$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.stop())
            } catch (exception: Throwable) {
              VpnEngineApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.vpn_engine_android.VpnEngineHostApi.getStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getStatus())
            } catch (exception: Throwable) {
              VpnEngineApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class VpnEngineApiPigeonStreamHandler<T>(
    val wrapper: VpnEngineApiPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface VpnEngineApiPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
/**
 * Host -> Flutter push streams.
 *
 * Two structurally SEPARATE channels, not one multiplexed channel:
 * `core_vpn_engine`'s `VpnEngine` Invariant 2 requires that a failure in the
 * statistics pipeline can never block or corrupt the connection-state
 * pipeline. Sharing a channel would re-couple them at the transport layer and
 * silently violate that invariant.
 *
 * Pigeon 29.0.6 generates a real `io.flutter.plugin.common.EventChannel` for
 * these (verified against the installed package, not assumed) — no hand-rolled
 * EventChannel and no method-channel polling.
 */
abstract class StateEventsStreamHandler : VpnEngineApiPigeonEventChannelWrapper<VpnStateEvent> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: StateEventsStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.vpn_engine_android.VpnEngineEventChannels.stateEvents"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = VpnEngineApiPigeonStreamHandler<VpnStateEvent>(streamHandler)
      EventChannel(messenger, channelName, VpnEngineApiPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from VpnEngineApiPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<VpnStateEvent>) {}

override fun onCancel(p0: Any?) {}
}
      
abstract class TrafficStatsEventsStreamHandler : VpnEngineApiPigeonEventChannelWrapper<TrafficStatsEvent> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: TrafficStatsEventsStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.vpn_engine_android.VpnEngineEventChannels.trafficStatsEvents"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = VpnEngineApiPigeonStreamHandler<TrafficStatsEvent>(streamHandler)
      EventChannel(messenger, channelName, VpnEngineApiPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
// Implement methods from VpnEngineApiPigeonEventChannelWrapper
override fun onListen(p0: Any?, sink: PigeonEventSink<TrafficStatsEvent>) {}

override fun onCancel(p0: Any?) {}
}
      
